### ISSUE TITLE
Repozyorium

### ISSUE THREAD

**Issue by kacperduras** [xNorbig/bnnyDrop#1]
Sugeruje usunąć zbędne pliki z mastera, tj. pliki związane ze serwerem, w repo zrobić jakiś układ folderów i plików, by nie było zamieszania. Proponuje w głównym katalogu trzymać tylko i wyłącznie:
* README.MD
* logo
* ew. plik z wersja skryptu, do autoaktualizatora.

Proponuje tez wypuszczac aktualizacja jako [release](https://github.com/xNorbig/bnnyDrop/releases)

**Comment by xNorbig** [comment]
Gotowe
