### ISSUE TITLE
Nie działają komendy, 0 errorów w konsoli

### ISSUE THREAD

**Issue by Trempek** [xNorbig/bnnyDrop#2]
Skrypt "działa"
Piszę normalnie Ładowanie bnnydrop v 1.0
autor także, errorów nie ma.
Ale jak wpisuję jakąkolwiek komendę to nic się nie dzieje
W konsoli echo
`[13:05:51] [Server thread/INFO]: Trempek issued server command: /drop
[13:05:51] [Server thread/INFO]: Trempek [df75db90-3f1b-484d-a616-9da56aff5935]: /drop`

**Comment by xNorbig** [comment]
Naprawione. Była literówka w skrypcie. Pobierz go na nowo.

**Comment by xNorbig** [comment]
Naprawione. Była literówka w skrypcie. Pobierz go na nowo.
